export const seedUsers = [
  {
    userId: 'U001',
    email: 'avi.nair@example.com',
    firstName: 'Avi',
    lastName: 'Nair',
    city: 'San Jose',
    state: 'CA',
    country: 'USA',
    communityId1: 'Velicham',
    communityId2: 'MMNJ',
    status: 'active',
    isActive: true,
  },
  {
    userId: 'U002',
    email: 'meera.iyer@example.com',
    firstName: 'Meera',
    lastName: 'Iyer',
    city: 'Greensboro',
    state: 'NC',
    country: 'USA',
    communityId1: 'GSO',
    status: 'active',
    isActive: true,
  },
  {
    userId: 'U003',
    email: 'arun.pillai@example.com',
    firstName: 'Arun',
    lastName: 'Pillai',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    communityId1: 'NANMA',
    status: 'active',
    isActive: true,
  },
  {
    userId: 'U004',
    email: 'nisha.menon@example.com',
    firstName: 'Nisha',
    lastName: 'Menon',
    city: 'Edison',
    state: 'NJ',
    country: 'USA',
    communityId1: 'MMNJ',
    status: 'active',
    isActive: true,
  },
  {
    userId: 'U005',
    email: 'vikram.shah@example.com',
    firstName: 'Vikram',
    lastName: 'Shah',
    city: 'Fremont',
    state: 'CA',
    country: 'USA',
    communityId1: 'Velicham',
    communityId2: 'GSO',
    status: 'active',
    isActive: true,
  },
  {
    userId: 'U006',
    email: 'anita.varma@example.com',
    firstName: 'Anita',
    lastName: 'Varma',
    city: 'Raleigh',
    state: 'NC',
    country: 'USA',
    communityId1: 'GSO',
    communityId2: 'NANMA',
    status: 'active',
    isActive: true,
  },
];
